[project]
name = "nish_my_history"
version = "1.0.0"
description = "A package to search through parquet form history data"
authors = [
    {name = "NishNovae", email = "raecrowned@gmail.com"},
]
dependencies = []
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
mh = "my_history.cli:argv"

[tool.pdm]
distribution = true
